name: Check and Create Release

on:
  workflow_dispatch: # Manually trigger the workflow

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read version from file
        id: read-version
        run: echo "::set-output name=version::$(cat .git/haloarmory_version)"

      - name: Get latest release
        id: get-latest-release
        run: |
          latest_release=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "::set-output name=latest_release::$latest_release"

      - name: Compare versions
        id: compare-versions
        run: |
          if [[ "${{ steps.read-version.outputs.version }}" != "${{ steps.get-latest-release.outputs.latest_release }}" ]]; then
            echo "Versions are different. Creating a new release..."
            echo "::set-output name=create_release::true"
          else
            echo "Versions match. No need to create a new release."
            echo "::set-output name=create_release::false"
          fi

  create-release:
    needs: check-version
    runs-on: ubuntu-latest
    if: ${{ needs.check-version.outputs.create_release == 'true' }}

    steps:
      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.read-version.outputs.version }}
          release_name: Release ${{ steps.read-version.outputs.version }}
          body: |
            Release notes for version ${{ steps.read-version.outputs.version }}
          draft: false
          prerelease: false

