# This is a basic workflow to help you get started with Actions

name: Upload via FTP

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The FTP upload job
jobs:
  web-deploy:
    name: 🎉 Upload to Ronin Networks
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.RONIN_FTP_HOST }}
        username: ${{ secrets.RONIN_FTP_USERNAME }}
        password: ${{ secrets.RONIN_FTP_PASSWORD }}
        local-dir: ./
        server-dir: garrysmod/addons/halorp-armory/
        dry-run: false
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          README.md
