name: Upload Haloarmory to Discord
on:
  workflow_dispatch
jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Zip Folder
        run: |
          cd ../
          cp -r ./HaloArmory-InDev ./haloarmory-v1
          rm -rf HaloArmory-InDev/Haloarmory.zip
          zip -r HaloArmory-InDev/Haloarmory.zip ./haloarmory-v1 -x ".git/*" ".github/*" "README.md"
      - name: Send Discord Update
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "Foo"
          embed-description: "Bar"
          embed-color: 3104415
          filename: "../Haloarmory.zip"
