name: Upload Haloarmory to Discord
on:
  workflow_dispatch
jobs:
  zip-n-push:
    name: Zip and Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Zip Folder
        run: |
          rm -rf Haloarmory.zip
          zip -r Haloarmory.zip . -x ".git/*" ".github/*" "README.md"
      - name: Send file to Discord channel
        uses: sinshutu/upload-to-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: Haloarmory.zip
